In [2]:
import sqlite3

# Create database file
conn = sqlite3.connect("agri_data.db")
cursor = conn.cursor()

print("SQLite Database Created Successfully!")

SQLite Database Created Successfully!

In [3]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS crop_data (
    Year INTEGER,
    State_Code INTEGER,
    State_Name TEXT,
    Dist_Code INTEGER,
    Dist_Name TEXT,

    Rice_Area REAL,
    Rice_Production REAL,
    Rice_Yield REAL,

    Wheat_Area REAL,
    Wheat_Production REAL,
    Wheat_Yield REAL,

    Maize_Area REAL,
    Maize_Production REAL,
    Maize_Yield REAL,

    Sugarcane_Production REAL,
    Oilseed_Production REAL,
    Groundnut_Production REAL,
    Cotton_Production REAL
);
""")

conn.commit()
print("Table Created Successfully!")

Table Created Successfully!

In [4]:
import pandas as pd

df = pd.read_csv("ICRISAT-District Level Data - ICRISAT-District Level Data (1).csv")

for index, row in df.iterrows():
    cursor.execute("""
        INSERT INTO crop_data VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, (
        row["Year"], row["State Code"], row["State Name"], row["Dist Code"], row["Dist Name"],
        row["RICE AREA (1000 ha)"], row["RICE PRODUCTION (1000 tons)"], row["RICE YIELD (Kg per ha)"],
        row["WHEAT AREA (1000 ha)"], row["WHEAT PRODUCTION (1000 tons)"], row["WHEAT YIELD (Kg per ha)"],
        row["MAIZE AREA (1000 ha)"], row["MAIZE PRODUCTION (1000 tons)"], row["MAIZE YIELD (Kg per ha)"],
        row["SUGARCANE PRODUCTION (1000 tons)"], row["OILSEEDS PRODUCTION (1000 tons)"],
        row["GROUNDNUT PRODUCTION (1000 tons)"], row["COTTON PRODUCTION (1000 tons)"]
    ))

conn.commit()
print("All rows inserted successfully!")

All rows inserted successfully!

In [5]:
query = """
SELECT State_Name,
       SUM(Rice_Production) AS Total_Rice
FROM crop_data
GROUP BY State_Name
ORDER BY Total_Rice DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

       State_Name  Total_Rice
0     West Bengal   544232.26
1   Uttar Pradesh   445597.62
2          Punjab   335040.10
3  Andhra Pradesh   315185.40
4      Tamil Nadu   291201.51

In [7]:
import sqlite3

# Create / connect to database file
conn = sqlite3.connect("agri_data.db")
cursor = conn.cursor()

print("Database created / connected successfully!")

Database created / connected successfully!

In [8]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS crop_data (
    Year INTEGER,
    State_Code INTEGER,
    State_Name TEXT,
    Dist_Code INTEGER,
    Dist_Name TEXT,
    Rice_Area REAL,
    Rice_Production REAL,
    Rice_Yield REAL,
    Wheat_Area REAL,
    Wheat_Production REAL,
    Wheat_Yield REAL,
    Maize_Area REAL,
    Maize_Production REAL,
    Maize_Yield REAL,
    Sugarcane_Production REAL,
    Oilseed_Production REAL,
    Groundnut_Production REAL,
    Cotton_Production REAL
);
""")

conn.commit()
print("Table crop_data created successfully!")

Table crop_data created successfully!

In [9]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('agri_data',), ('crops',), ('sqlite_sequence',), ('crop_data',)]

In [10]:
import pandas as pd

df = pd.read_csv("ICRISAT-District Level Data - ICRISAT-District Level Data (1).csv")

for index, row in df.iterrows():
    cursor.execute("""
        INSERT INTO crop_data VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    """, (
        row["Year"], row["State Code"], row["State Name"], row["Dist Code"], row["Dist Name"],
        row["RICE AREA (1000 ha)"], row["RICE PRODUCTION (1000 tons)"], row["RICE YIELD (Kg per ha)"],
        row["WHEAT AREA (1000 ha)"], row["WHEAT PRODUCTION (1000 tons)"], row["WHEAT YIELD (Kg per ha)"],
        row["MAIZE AREA (1000 ha)"], row["MAIZE PRODUCTION (1000 tons)"], row["MAIZE YIELD (Kg per ha)"],
        row["SUGARCANE PRODUCTION (1000 tons)"], row["OILSEEDS PRODUCTION (1000 tons)"],
        row["GROUNDNUT PRODUCTION (1000 tons)"], row["COTTON PRODUCTION (1000 tons)"]
    ))

conn.commit()
print("All data inserted into table!")

All data inserted into table!

In [11]:
pd.read_sql_query("SELECT * FROM crop_data LIMIT 5;", conn)

,Year,State_Code,State_Name,Dist_Code,Dist_Name,Rice_Area,Rice_Production,Rice_Yield,Wheat_Area,Wheat_Production,Wheat_Yield,Maize_Area,Maize_Production,Maize_Yield,Sugarcane_Production,Oilseed_Production,Groundnut_Production,Cotton_Production
0,1966,14,Chhattisgarh,1,Durg,548.0,185.0,337.59,44.0,20.0,454.55,3.0,2.0,666.67,1.6,-1.0,0.1,0.0
1,1967,14,Chhattisgarh,1,Durg,547.0,409.0,747.71,50.0,26.0,520.00,3.0,3.0,1000.00,1.2,-1.0,0.1,0.0
2,1968,14,Chhattisgarh,1,Durg,556.3,468.0,841.27,53.7,30.0,558.66,2.8,2.0,714.29,1.0,-1.0,0.1,0.0
3,1969,14,Chhattisgarh,1,Durg,563.4,400.8,711.40,49.4,26.5,536.44,2.7,2.3,851.85,1.9,14.9,0.1,0.0
4,1970,14,Chhattisgarh,1,Durg,571.6,473.6,828.55,44.2,29.0,656.11,2.5,3.3,1320.00,1.4,24.3,0.1,0.0

# 1. YEARS WISE RICE PRODUCTION (TOP 3 STATE )

In [13]:
query1 = """
SELECT Year, State_Name,
       SUM(Rice_Production) AS Total_Rice
FROM crop_data
GROUP BY Year, State_Name
ORDER BY Year ASC, Total_Rice DESC;
"""

pd.read_sql_query(query1, conn)

      Year        State_Name  Total_Rice
0     1966       West Bengal     9638.80
1     1966        Tamil Nadu     7586.00
2     1966            Orissa     7383.58
3     1966    Andhra Pradesh     6428.00
4     1966     Uttar Pradesh     4947.00
...    ...               ...         ...
1033  2017           Gujarat     3779.62
1034  2017       Uttarakhand     1264.20
1035  2017            Kerala     1042.64
1036  2017         Rajasthan      901.86
1037  2017  Himachal Pradesh      229.56

[1038 rows x 3 columns]

# 2. TOP 5 DISTRICTS WHEAT YIELD 5 YEARS INCREASE

In [14]:
query2 = """
SELECT Dist_Name,
       AVG(Wheat_Yield) AS Avg_Wheat_Yield
FROM crop_data
WHERE Year >= (SELECT MAX(Year) - 5 FROM crop_data)
GROUP BY Dist_Name
ORDER BY Avg_Wheat_Yield DESC
LIMIT 5;
"""

pd.read_sql_query(query2, conn)

  Dist_Name  Avg_Wheat_Yield
0   Sangrur      5187.696667
1  Bhatinda      4911.691667
2  Ludhiana      4907.826667
3  Ferozpur      4883.835000
4   Patiala      4847.520000

# 3. STATES WITH HIGHEST GROWTH IN OILSEED PRODUCTION (LAST 5 YEARS)

In [15]:
query3 = """
SELECT State_Name,
       (MAX(Oilseed_Production) - MIN(Oilseed_Production)) AS Oilseed_Growth
FROM crop_data
WHERE Year >= (SELECT MAX(Year) - 5 FROM crop_data)
GROUP BY State_Name
ORDER BY Oilseed_Growth DESC
LIMIT 5;
"""

pd.read_sql_query(query3, conn)

       State_Name  Oilseed_Growth
0         Gujarat         1712.92
1  Andhra Pradesh         1123.85
2     Maharashtra         1045.70
3       Rajasthan          968.51
4  Madhya Pradesh          840.85

# 4. AREA WISH PRODUCTION CORRELATION (RICE, WHEAT,MAIZE)

In [17]:
query4 = """
SELECT 
    Rice_Area, Rice_Production,
    Wheat_Area, Wheat_Production,
    Maize_Area, Maize_Production
FROM crop_data;
"""

df_corr = pd.read_sql_query(query4, conn)
df_corr.head()

,Rice_Area,Rice_Production,Wheat_Area,Wheat_Production,Maize_Area,Maize_Production
0,548.0,185.0,44.0,20.0,3.0,2.0
1,547.0,409.0,50.0,26.0,3.0,3.0
2,556.3,468.0,53.7,30.0,2.8,2.0
3,563.4,400.8,49.4,26.5,2.7,2.3
4,571.6,473.6,44.2,29.0,2.5,3.3

In [18]:
df_corr.corr()

,Rice_Area,Rice_Production,Wheat_Area,Wheat_Production,Maize_Area,Maize_Production
Rice_Area,1.000000,0.832515,0.013339,0.067000,-0.065428,-0.007391
Rice_Production,0.832515,1.000000,0.138433,0.265873,-0.083338,0.050791
Wheat_Area,0.013339,0.138433,1.000000,0.910643,0.094132,0.027981
Wheat_Production,0.067000,0.265873,0.910643,1.000000,0.027197,0.012730
Maize_Area,-0.065428,-0.083338,0.094132,0.027197,1.000000,0.802003
Maize_Production,-0.007391,0.050791,0.027981,0.012730,0.802003,1.000000

# EARLY PRODUCTION GROWTH OF COTTON (TOP STATES )

In [19]:
query5 = """
SELECT Year, State_Name,
       SUM(Cotton_Production) AS Total_Cotton
FROM crop_data
GROUP BY Year, State_Name
ORDER BY Year ASC, Total_Cotton DESC;
"""

pd.read_sql_query(query5, conn)

      Year        State_Name  Total_Cotton
0     1966           Gujarat        504.00
1     1966       Maharashtra        394.00
2     1966            Punjab        263.20
3     1966        Tamil Nadu        124.00
4     1966           Haryana        108.60
...    ...               ...           ...
1033  2017            Kerala          0.04
1034  2017       Uttarakhand          0.00
1035  2017         Jharkhand          0.00
1036  2017  Himachal Pradesh          0.00
1037  2017             Bihar          0.00

[1038 rows x 3 columns]

# 6. DISTRICTS WITH HIGHEST GROUNDNUT PRODUCTION (YEAR=2020)

In [23]:
query6 = """
SELECT Dist_Name, Groundnut_Production
FROM crop_data
WHERE Year = 2020
ORDER BY Groundnut_Production DESC
LIMIT 10;
"""

pd.read_sql_query(query6, conn)

Empty DataFrame
Columns: [Dist_Name, Groundnut_Production]
Index: []

# 7. ANNUAL AVERAGE MAIZE YIELD (ACROSS ALL STATES)

In [24]:
query7 = """
SELECT Year,
       AVG(Maize_Yield) AS Avg_Maize_Yield
FROM crop_data
GROUP BY Year
ORDER BY Year ASC;
"""

pd.read_sql_query(query7, conn)

    Year  Avg_Maize_Yield
0   1966       734.266355
1   1967       869.540323
2   1968       709.261774
3   1969       781.476645
4   1970      1094.176206
5   1971       848.642862
6   1972       895.126141
7   1973       886.839614
8   1974       852.936592
9   1975      1026.008875
10  1976       966.653537
11  1977       946.525113
12  1978       964.877170
13  1979       984.162058
14  1980      1067.085402
15  1981      1119.513826
16  1982      1189.239904
17  1983      1314.558264
18  1984      1226.566817
19  1985      1057.788746
20  1986      1078.989936
21  1987       945.443955
22  1988      1145.877492
23  1989      1324.732186
24  1990      1235.363452
25  1991      1157.018419
26  1992      1450.823000
27  1993      1345.807323
28  1994      1211.294774
29  1995      1344.002336
30  1996      1443.180098
31  1997      1409.269325
32  1998      1419.082219
33  1999      1516.950772
34  2000      1556.488296
35  2001      1758.419775
36  2002      1384.691961
37  2003      1704.555145
38  2004      1619.802444
39  2005      1702.612765
40  2006      1678.536302
41  2007      1990.170257
42  2008      1935.154823
43  2009      1764.596849
44  2010      2078.251383
45  2011      2064.950257
46  2012      2137.156527
47  2013      2343.496323
48  2014      2400.829194
49  2015      2260.076323
50  2016      2463.027685
51  2017      2852.332419

# 8. TOTAL OILSEED PRODUCTION BY STATE

In [25]:
query8 = """
SELECT State_Name,
       SUM(Oilseed_Production) AS Total_Oilseed_Production
FROM crop_data
GROUP BY State_Name
ORDER BY Total_Oilseed_Production DESC;
"""

pd.read_sql_query(query8, conn)

          State_Name  Total_Oilseed_Production
0     Madhya Pradesh                 307189.58
1            Gujarat                 252448.02
2          Rajasthan                 245453.72
3        Maharashtra                 191135.82
4     Andhra Pradesh                 153776.18
5         Tamil Nadu                 110550.06
6          Karnataka                 105198.08
7             Orissa                  56907.54
8      Uttar Pradesh                  48031.96
9            Haryana                  48013.20
10         Telangana                  44356.64
11       West Bengal                  30647.14
12            Punjab                  15600.84
13             Assam                  13990.86
14      Chhattisgarh                  11223.16
15             Bihar                   5199.84
16            Kerala                   2385.54
17         Jharkhand                    818.70
18  Himachal Pradesh                    594.64
19       Uttarakhand                    458.44

# 9. TOP DISTRICTS WITH HIGHEST RICE YIELD

In [26]:
query9 = """
SELECT Dist_Name, Rice_Yield
FROM crop_data
ORDER BY Rice_Yield DESC
LIMIT 10;
"""

pd.read_sql_query(query9, conn)

      Dist_Name  Rice_Yield
0  Thirunelveli     5653.83
1  Thirunelveli     5653.83
2       Saharsa     5542.32
3       Saharsa     5542.32
4   Kanyakumari     5421.78
5   Kanyakumari     5421.78
6          Rewa     5159.93
7          Rewa     5159.93
8         Salem     5129.68
9         Salem     5129.68

# 10. COMPARE WHEAT VS RICE PRODUCTION FOR TOP STATES (10 YEARS)

In [27]:
query10 = """
SELECT Year,
       State_Name,
       SUM(Rice_Production) AS Rice_Prod,
       SUM(Wheat_Production) AS Wheat_Prod
FROM crop_data
GROUP BY Year, State_Name
ORDER BY Year ASC, Rice_Prod DESC, Wheat_Prod DESC;
"""

pd.read_sql_query(query10, conn)

      Year        State_Name  Rice_Prod  Wheat_Prod
0     1966       West Bengal    9638.80       91.10
1     1966        Tamil Nadu    7586.00        0.00
2     1966            Orissa    7383.58       28.38
3     1966    Andhra Pradesh    6428.00        1.20
4     1966     Uttar Pradesh    4947.00     7887.20
...    ...               ...        ...         ...
1033  2017           Gujarat    3779.62     6202.12
1034  2017       Uttarakhand    1264.20     1553.92
1035  2017            Kerala    1042.64        0.00
1036  2017         Rajasthan     901.86    22560.96
1037  2017  Himachal Pradesh     229.56     1207.18

[1038 rows x 4 columns]